rest:
  auth-open: true #jwt鉴权机制是否开启
  sign-open: true #签名机制是否开启

jwt:
  header: Authorization   #http请求头所需要的字段
  secret: mySecret        #jwt秘钥
  expiration: 604800      #7天 单位:秒
  auth-path: auth         #认证请求的路径
  md5-key: randomKey      #md5加密混淆key

server:
  port: 80 #项目端口

logging:
  level.root: info
  level.com.stylefeng: debug
  path: logs/
  file: cs-rest.log